### ISSUE TITLE
[REQUEST] /diving & /moim

### ISSUE THREAD

**Issue by JHyeon0915** [TangSquad/back-end#55]
# 요청사항

- [x] 모임과 다이빙에 thumbnailUrl, currentPeople추가해주세요
- [x] <strong>moim 섹션에 moim/{moimId} 추가해주세요</strong>
- [x] <strong>diving 섹션에 /diving/all 과 /diving/joined 추가해주세요</strong>
- [x] id 출력시 id와 divingId&moimId 둘 중 하나로만 통일해 주세요
- [x] 자격증 제한 licenseLimit과 limitLicense 중 하나로만 통일해 주세요

# 요청사항 반영 후 예시

```
{
    "id": 0,  // id로 통일했을 경우
    "userId": 0,
    "thumbnailUrl": 'string',  // 추가
    "anonymous": true,
    "moimName": "string",
    "moimIntro": "string",
    "moimDetails": "string",
    "currentPeople": 0,  // 추가
    "limitPeople": 0,
    "expense": 0,
    "licenseLimit": "string",  // licenseLimit으로 통일했을 경우
    "locationOne": "string",
    "locationTwo": "string",
    "locationThree": "string",
    "age": "string",
    "moodOne": "string",
    "moodTwo": "string"
  }
```

```
{
    "id": 0,  // id로 통일했을 경우
    "userId": 0,
    "thumbnailUrl: 'string',  // 추가
    "divingName": "string",
    "divingIntro": "string",
    "age": "string",
    "moodOne": "string",
    "moodTwo": "string",
    "currentPeople": 0,  // 추가
    "limitPeople": 0,
    "limitLicense": "string",  // licenseLimit으로 통일했을 경우
    "startDate": "2024-10-20",
    "endDate": "2024-10-20",
    "location": "string"
}
```

**Comment by junnie082** [comment]
<img width="457" alt="스크린샷 2024-11-06 오전 2 59 10" src="https://github.com/user-attachments/assets/277c13c6-0c1c-4807-bf20-9d2ef43d4088">

**Comment by gomdoricake** [comment]
## Moim Response

<img width="298" alt="스크린샷 2024-11-06 오전 3 10 51" src="https://github.com/user-attachments/assets/8aeb08a9-7867-4392-8ed2-373c8293f15c">

**Comment by gomdoricake** [comment]
## Diving Response

<img width="346" alt="스크린샷 2024-11-06 오전 3 24 11" src="https://github.com/user-attachments/assets/5763de66-ca63-4d57-aee4-4e77952e7ae1">
